# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: When a shell is not enough
author: Xavier Garcia
description: >- # this means to ignore newlines until "baseurl:"
  Unix engineer with interests in Information Security and Ethical Hacking.
  I love to break and fix things :)  

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: shellguardians
github_username:  xgarcias

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

jekyll-archives:
  enabled:
    - year
    - month
  layouts:
    year: 'year'
    month: 'month'
  permalinks:
    year: '/archives/:year/'
    month: '/archives/:year/:month/'


permalink: /:year/:month/:title.html
